[versions]
nexus = "1.0.0"

[libraries]
slf4j="org.slf4j:slf4j-api:1.7.30"
testng="org.testng:testng:7.4.0"
logbackClassic="ch.qos.logback:logback-classic:1.0.13"
janino="org.codehaus.janino:janino:2.6.1"

plugins-nexus = { module = "io.github.gradle-nexus:publish-plugin", version.ref = "nexus"}

