name: Main
on:
  push:
    branches:
    - master
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 8
    - uses: gradle/wrapper-validation-action@v1.0.3
    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: build --scan
        wrapper-cache-enabled: true
        dependencies-cache-enabled: true
        configuration-cache-enabled: true
